# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=240, null=True)),
                ('number', models.CharField(blank=True, max_length=40, null=True)),
                ('whatsAppN', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(blank=True, max_length=240, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('model', models.CharField(blank=True, choices=[('1', 'Perodua Myvi'), ('2', 'Perodua Alza'), ('3', 'Perodua Axia'), ('4', 'Honda City'), ('5', 'Honda Civic')], max_length=40, null=True)),
                ('seat', models.IntegerField(default=5)),
                ('ac', models.BooleanField(default=True)),
                ('availability', models.BooleanField(default=True)),
                ('address', models.CharField(blank=True, max_length=240, null=True)),
                ('per_hour', models.IntegerField(default=10)),
                ('SpacialDiscount', models.CharField(blank=True, max_length=240, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_owner', to='home.CarOwner')),
            ],
        ),
    ]
