# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171028_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
