# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20171030_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='per_day',
            field=models.IntegerField(default=10),
        ),
    ]
