# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20171031_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='address',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='address_text',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
